# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
pod 'DoraemonKit/Core', git: 'https://git.toolsfdg.net/fe/DoraemonKit.git', tag: '1.2.4-en-fix'
  pod 'DoraemonKit/WithLoad', git: 'https://git.toolsfdg.net/fe/DoraemonKit.git', tag: '1.2.4-en-fix'
  pod 'DoraemonKit/WithMLeaksFinder', git: 'https://git.toolsfdg.net/fe/DoraemonKit.git', tag: '1.2.4-en-fix'
  # Pods for Demo

end
